---
title: "Final Project"
author: "Heather Motro"
date: "2025-11-06"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo = FALSE, include = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stringr)
library(lubridate)
library(knitr)
library(here)
```

```{r load data, include = FALSE, echo = FALSE}
#The location I'm using is in upstate NY, near Allen Mountain. Fujacks Road, Newcomb, Essex County, NY, United States of America
Bart_mass_04 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-04.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_massdata.2016-04.basic.20241118T171259Z.csv")
Bart_mass_05 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-05.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_massdata.2016-05.basic.20241118T023817Z.csv")
Bart_mass_06 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-06.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_massdata.2016-06.basic.20241118T031958Z.csv")
Bart_mass_07 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-07.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_massdata.2016-07.basic.20241118T150320Z.csv")
Bart_mass_09 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-09.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_massdata.2016-09.basic.20241118T150721Z.csv")
Bart_mass_10 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-10.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_massdata.2016-10.basic.20241118T095547Z.csv")
Bart_mass_11 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-11.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_massdata.2016-11.basic.20241118T181203Z.csv")
Bart_pertrap_04 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-04.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_pertrap.basic.20241118T171259Z.csv")
Bart_pertrap_05 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-05.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_pertrap.basic.20241118T023817Z.csv")
Bart_pertrap_06 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-06.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_pertrap.basic.20241118T031958Z.csv")
Bart_pertrap_07 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-07.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_pertrap.basic.20241118T150320Z.csv")
Bart_pertrap_09 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-09.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_pertrap.basic.20241118T150721Z.csv")
Bart_pertrap_10 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-10.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_pertrap.basic.20241118T095547Z.csv")
Bart_pertrap_11 <- read_csv("C:/Users/hmotr/OneDrive/Documents/UGA/FANR_8950-final-project/NEON_litterfall/NEON.D01.BART.DP1.10033.001.2016-11.basic.20250129T000730Z.RELEASE-2025/NEON.D01.BART.DP1.10033.001.ltr_pertrap.basic.20241118T181203Z.csv")
head(Bart_mass_04)
head(Bart_pertrap_04)
```

```{r join data, echo = FALSE}
#getting all mass data into one df
mass_all <- bind_rows(
  Bart_mass_04, Bart_mass_05, Bart_mass_06, Bart_mass_07, Bart_mass_09, Bart_mass_10, Bart_mass_11) %>%
  arrange(collectDate, weighDate, namedLocation, plotID, trapID, functionalGroup) %>%
    select(weighDate, setDate, collectDate, ovenStartDate, ovenEndDate, plotID, trapID, sampleCondition, massSampleID, functionalGroup, dryMass, qaDryMass, remarks) #only keep meaningful columns


#getting all trap data into one df
trap_all <- bind_rows(Bart_pertrap_04, Bart_pertrap_05, Bart_pertrap_06, Bart_pertrap_07, Bart_pertrap_09, Bart_pertrap_10, Bart_pertrap_11) %>%
  arrange(plotID, trapID) %>%
  select(namedLocation, plotID, subplotID, trapID, decimalLatitude, decimalLongitude, elevation, nlcdClass, plotType, coordinateUncertainty, elevationUncertainty, date, targetTaxaPresent, trapType, trapPlacement, trapSize, remarks)

#merging mass and trap dataframes
mass_trap <- merge(mass_all, trap_all, by = "trapID") %>%
  arrange(collectDate, trapID)
```
```{r I dont want this to show up, echo = FALSE, include = FALSE}
#checking what data class each vector is
str(mass_trap)
```

```{r join data cont, echo = FALSE}
#Adding new column that just shows month
mass_trap$month <- as.numeric(format(mass_trap$collectDate, "%m"))

#Ordering columns
mass_trap <- mass_trap %>%
  select(month, trapID, functionalGroup, nlcdClass, trapType, trapSize, dryMass, everything())
```

```{r time differences, echo = FALSE}
#Length of time between setting trap and collecting litter
mass_trap$accumulation_days <- as.numeric(mass_trap$collectDate - mass_trap$setDate)
```

```{r cleaning up an outlier, include = FALSE}
#Note: After putting everything in a table, I saw an unusually high mean and wanted to go back and check it.

october_leaves_dryMass <- mass_trap %>%
  filter(month == 10, functionalGroup == "Leaves") %>%
  arrange(desc(dryMass))

head(october_leaves_dryMass)

mass_trap %>% filter(dryMass > 0.99) %>% arrange(desc(dryMass)) %>% select(dryMass, month, functionalGroup, accumulation_days)

#After viewing, I suspected this was recorded in the wrong units as all values were in the tens rather than the tenths/hundreths as other values. But then I thought about the context - maybe it would make sense for there to be a lot more leaf litter collected in October.
```

```{r unused cleaning, eval = FALSE, include = FALSE}
#Just saving this here in case I want to use it.
#Correcting
mass_trap <- mass_trap %>% 
  mutate(
    dryMass_clean =
    ifelse(month == 10 & functionalGroup == "Leaves", dryMass / 1000, dryMass)
  )

mass_trap %>%
  filter(month == 10, functionalGroup == "Leaves") %>% select(dryMass_clean) %>%
           arrange(desc(dryMass_clean))
```

```{r dry mass per days collected, echo = FALSE, include = FALSE}
#Creating a function that makes a new column for dry mass per days the trap collected litter
calc_drymass_rate <- function(placeholder) { #Note to self: fill in any df for 'placeholder'
  placeholder %>%
    mutate(dryMass_per_day = ifelse(is.na(accumulation_days) | accumulation_days == 0, NA, dryMass / accumulation_days))
}
 #Note to self: ifelse ensures that I don't divide when there are 0 accumulation days or accumulation day is NA. I don't see that anywhere in the data, but just in case.
  
#Run the function 
mass_trap <- calc_drymass_rate(mass_trap)
head(mass_trap$dryMass_per_day) #note to self: This is litter accumulation in g/day

```

```{r summary dry mass per day per month, echo = FALSE}
month_summary <- mass_trap %>%
  group_by(month, functionalGroup) %>%
  summarize(mean_dryMass_per_day = mean(dryMass_per_day, na.rm = T), .groups = "drop") #AI Assistance: Looked up how to remove a "summarize" message from HTML doc, it suggested .groups = "drop"

#Renaming month numbers to month names
month_summary <- month_summary %>% 
  mutate(month_name = month.name[month])

#Converting to ordered factor
month_summary <- month_summary %>%
  mutate(month_name = factor(month_name, levels = month.name))

#Creating nest
month_summary_nest <- month_summary %>%
  group_by(month_name) %>%
  nest()

#Reorder by functional group with decreasing mean
month_summary_nest <- month_summary_nest %>%
  mutate(
    data = map(data, ~ .x %>%
                 mutate(functionalGroup = fct_reorder(functionalGroup, mean_dryMass_per_day, .desc = T)))
  )
#Note to self: 'map' works like 'across' for a nest. 'data' is from the nest. It contains all the tibbles. '~.x' is a placeholder for each nested tibble

#Using for loop to turn this into a table
n_months <- nrow(month_summary_nest)  #AI Assistance: I wasn't sure how to get started on this, ChatGPT suggested I start by creating a separate df with the number of months for the loop to work with.
for (i in 1:n_months){
  month_data <- month_summary_nest$data[[i]] %>%
    arrange(desc(mean_dryMass_per_day))
month_data %>%
  select('Litter Source Functional Group' = functionalGroup, 'Mean Litter Mass Accumulated (g/day)' = mean_dryMass_per_day) %>%
  kable(caption = paste("Mean Litterfall (g/day)", month_summary_nest$month_name[i])) %>% 
  print()}

```

```{r standard deviation, echo = FALSE}
month_summary_sd <- mass_trap %>%
  group_by(month, functionalGroup) %>%
  summarize(
    mean_dryMass_per_day = mean(dryMass_per_day, na.rm = TRUE),
    sd_dryMass_per_day = sd(dryMass_per_day, na.rm = TRUE),
    n = n(), .groups = "drop") %>% 
  mutate(month_name = factor(month.name[month], levels = month.name)) #Had to create the ordered factor again

month_summary_sd %>%
  select(
    Month = month_name,
    `Litter Source` = functionalGroup,
    'Mean Dry Mass per Day' = mean_dryMass_per_day,
    'Standard Deviation' = sd_dryMass_per_day,
    n
  ) %>%
  kable(
    caption = "Monthly Standard Deviation and Mean Daily Litterfall by Functional Group",
    digits = 3
  )
```

```{r plots, echo = FALSE}
library(RColorBrewer)

ggplot(month_summary,
       aes(x = month_name, y = mean_dryMass_per_day, fill = functionalGroup)) +
  geom_bar(stat = "identity", position = "dodge") +
scale_fill_brewer(palette = "Dark2") +
  labs(title = "Daily Litterfall Accumulation in Bartlett Experimental Forest, 2016",
       x = "Month",
       y = "Mean dry litter mass (g/day)",
       fill = "Litter Source")

#standard error plot

ggplot(month_summary_sd,
       aes(x = month_name,
           y = sd_dryMass_per_day,
           color = functionalGroup,
           group = functionalGroup,
           size = sd_dryMass_per_day)) +
  geom_point(alpha = 0.7) +
  scale_color_brewer(palette = "Dark2") +
  scale_size_continuous(range = c(2, 12), guide = "none") +
  labs(title = "Monthly Standard Deviation of Daily Litterfall",
       x = "Month",
       y = "SD of dry litter mass (g/day)",
       color = "Functional Group")

#Replicating plots without the October outlier

month_summary_no_outlier <- month_summary %>%
  filter(!(month == 10 & mean_dryMass_per_day > 0.99))
month_summary_no_outlier <- month_summary_no_outlier %>%
  filter(!(month == 11 & mean_dryMass_per_day > 0.8))

month_summary_sd_no_outlier <- month_summary_sd %>%
  filter(!(month == 10 & mean_dryMass_per_day > 0.99))
month_summary_sd_no_outlier <- month_summary_sd_no_outlier %>%
  filter(!(month == 11 & mean_dryMass_per_day > 0.8))
  
ggplot(month_summary_no_outlier,
       aes(x = month_name, y = mean_dryMass_per_day, fill = functionalGroup, group = functionalGroup)) +
  geom_bar(stat= "identity", position = "dodge") +
  scale_fill_brewer(palette = "Dark2")  +
  labs(x = "Month", y = "Mean dry litter mass (g/day)", fill = "Litter Source", title = "Daily Litterfall Accumulation in Bartlett Experimental Forest, 2016, outliers excluded", subtitle = "Outliers from high autumn leaf fall excluded", caption = "Outliers: October Leaves 3.41 g/day, November Leaves 0.82 g/day")


ggplot(month_summary_sd_no_outlier,
       aes(x = month_name,
           y = sd_dryMass_per_day,
           color = functionalGroup,
           group = functionalGroup,
           size = sd_dryMass_per_day)) +
  geom_point(alpha = 0.7) +
  scale_color_brewer(palette = "Dark2") +
  scale_size_continuous(range = c(2, 12), guide = "none") +   # adjust dot size range
  labs(title = "Monthly Standard Deviation of Daily Litterfall, outliers excluded",
       x = "Month",
       y = "SD of dry litter mass (g/day)",
       color = "Functional Group", subtitle = "Outliers from high autumn leaf fall excluded")
```

Notes for myself: Basically I just need a report that summarizes info in the dataset. I need "quantitative information summarizing information in the data set." I don't have to analyze it, I just have to showcase it and have it ready for future analyses. Pretend it's an end-of-season report. I am going to focus on: leaf litter per trap.
